ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --timeout=120
  inifile: /app/pytest.ini
  rootdir: /app
